<?php
/**
 * ErrorV2Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Klarna\Payments
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * klarna-payments
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20200630142900
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Klarna\Payments;

/**
 * ErrorV2Test Class Doc Comment
 *
 * @category    Class
 * @description ErrorV2
 * @package     Klarna\Payments
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ErrorV2Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ErrorV2"
     */
    public function testErrorV2()
    {
    }

    /**
     * Test attribute "authorized_payment_method"
     */
    public function testPropertyAuthorizedPaymentMethod()
    {
    }

    /**
     * Test attribute "correlation_id"
     */
    public function testPropertyCorrelationId()
    {
    }

    /**
     * Test attribute "error_code"
     */
    public function testPropertyErrorCode()
    {
    }

    /**
     * Test attribute "error_messages"
     */
    public function testPropertyErrorMessages()
    {
    }

    /**
     * Test attribute "fraud_status"
     */
    public function testPropertyFraudStatus()
    {
    }

    /**
     * Test attribute "reason"
     */
    public function testPropertyReason()
    {
    }
}
