<?php
/**
 * OptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Klarna
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * klarna-payments
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20200630142900
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Klarna;

/**
 * OptionsTest Class Doc Comment
 *
 * @category    Class
 * @description Options
 * @package     Klarna
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OptionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Options"
     */
    public function testOptions()
    {
    }

    /**
     * Test attribute "color_border"
     */
    public function testPropertyColorBorder()
    {
    }

    /**
     * Test attribute "color_border_selected"
     */
    public function testPropertyColorBorderSelected()
    {
    }

    /**
     * Test attribute "color_details"
     */
    public function testPropertyColorDetails()
    {
    }

    /**
     * Test attribute "color_text"
     */
    public function testPropertyColorText()
    {
    }

    /**
     * Test attribute "radius_border"
     */
    public function testPropertyRadiusBorder()
    {
    }
}
