<?php
/**
 * OrdersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Klarna\Payments
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * klarna-payments
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20200630142900
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Klarna\Payments;

use \Klarna\Payments\Configuration;
use \Klarna\Payments\ApiException;
use \Klarna\Payments\ObjectSerializer;

/**
 * OrdersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Klarna\Payments
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrdersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cancelAuthorization
     *
     * Cancel an existing authorization.
     *
     */
    public function testCancelAuthorization()
    {
    }

    /**
     * Test case for createOrder
     *
     * Create a new order.
     *
     */
    public function testCreateOrder()
    {
    }

    /**
     * Test case for purchaseToken
     *
     * Generate a consumer token.
     *
     */
    public function testPurchaseToken()
    {
    }
}
