<?php
/**
 * SessionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Klarna
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * klarna-payments
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20200630142900
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Klarna;

use \Klarna\Configuration;
use \Klarna\ApiException;
use \Klarna\ObjectSerializer;

/**
 * SessionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Klarna
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SessionsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createCreditSession
     *
     * Create a new credit session.
     *
     */
    public function testCreateCreditSession()
    {
    }

    /**
     * Test case for readCreditSession
     *
     * Read an existing credit session.
     *
     */
    public function testReadCreditSession()
    {
    }

    /**
     * Test case for updateCreditSession
     *
     * Update an existing credit session.
     *
     */
    public function testUpdateCreditSession()
    {
    }
}
